/**
 * The Tamarind House: the home journey now foregrounds the Abu Shagara restaurant, its three signature dishes, and clear ordering/location actions.
 * Motion remains tactile and appetising: imagery breathes, editorial blocks rise gently, and cards respond like objects on a dining table.
 */
import { ArrowDownRight, ArrowUpRight, ChevronRight, Clock3, MapPin, Phone } from "lucide-react";
import { Link } from "wouter";
import { SectionTitle } from "@/components/SectionTitle";
import { useLanguage } from "@/contexts/LanguageContext";

const dishes = [
  { name: "Chettinad Chilly Chicken", ta: "செட்டிநாடு சில்லி சிக்கன்", caption: "Crisp chicken, red chilli, curry leaf and a peppery finish.", taCaption: "மொறுமொறு சிக்கன், செம்மிளகாய், கறிவேப்பிலை, மிளகு மணம்.", image: "/manus-storage/karaikudi-chilly-chicken_7ec628a9.jpg", number: "01" },
  { name: "Mutton Milagu Masala", ta: "மட்டன் மிளகு மசாலா", caption: "Deep-roasted mutton, black pepper and slow-built masala.", taCaption: "வறுத்த மட்டன், கருமிளகு, மெதுவாக உருவான மசாலா.", image: "/manus-storage/karaikudi-milagu-masala_7361a2a6.jpg", number: "02" },
  { name: "Chennai Chicken Lollipop", ta: "சென்னை சிக்கன் லாலிபாப்", caption: "A crisp, red-glazed favourite with plenty of fire.", taCaption: "காரமான செம்மை glaze கொண்ட மொறுமொறு சிறப்பு.", image: "/manus-storage/karaikudi-chicken-lollipop_39404e72.jpg", number: "03" },
];

export default function Home() {
  const { t } = useLanguage();
  return <>
    <section className="relative flex min-h-[780px] items-end overflow-hidden bg-[#16090a] px-5 pb-14 pt-32 text-[#fffaf2] sm:px-8 sm:pb-20 lg:min-h-[850px] lg:px-12">
      <img src="/manus-storage/karaikudi-hero_39b8be16.jpg" alt="Chettinad feast with chicken curry, parotta and whole spices on a dark teak table" className="hero-image-motion absolute inset-0 h-full w-full object-cover object-[60%_center]" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(18,7,8,0.86)_0%,rgba(18,7,8,0.60)_38%,rgba(18,7,8,0.12)_72%),linear-gradient(0deg,rgba(18,7,8,0.62)_0%,transparent_45%)]" />
      <div className="hero-arch tile-orbit absolute -right-[10%] top-[21%] hidden h-[58%] w-[34%] border border-[#d3a56d]/35 lg:block" />
      <div className="relative mx-auto w-full max-w-[1320px]"><p className="motion-reveal motion-delay-1 eyebrow text-[#d3a56d]">{t("Abu Shagara · Sharjah, UAE", "அபு ஷகரா · ஷார்ஜா, UAE")}</p><h1 className="motion-reveal motion-delay-2 mt-4 max-w-5xl font-display text-[clamp(4.1rem,8.9vw,8rem)] leading-[0.79] tracking-[-0.07em]">{t("The Real Authentic Taste of Chettinad Cuisine", "செட்டிநாடு உணவு வகைகளின் உண்மையான அசல் சுவை")}</h1><p className="motion-reveal motion-delay-3 mt-7 max-w-lg text-base leading-7 text-[#fff6e9]/78 sm:text-lg">{t("The only restaurant where you can experience real and authentic taste of Chettinad cuisine in the heart of Sharjah.", "ஷார்ஜாவின் இதயத்தில் உண்மையான செட்டிநாடு சமையலின் சுவையை அனுபவிக்கக்கூடிய ஒரே உணவகம்.")}</p><div className="motion-reveal motion-delay-4 mt-9 flex flex-wrap gap-3"><Link href="/order" className="button-primary"><span>{t("Order online", "ஆன்லைனில் ஆர்டர்")}</span><ArrowUpRight size={17} /></Link><Link href="/location" className="button-ghost"><span>{t("Find us", "எங்களைக் கண்டுபிடியுங்கள்")}</span><MapPin size={16} /></Link></div></div>
      <div className="absolute bottom-6 right-5 hidden items-center gap-3 text-[10px] font-bold uppercase tracking-[0.18em] text-[#fff6e9]/60 sm:flex lg:right-12"><span>{t("Scroll for the story", "கதைக்காக நகர்த்தவும்")}</span><ArrowDownRight size={16} /></div>
    </section>

    <section className="relative overflow-hidden bg-[#f7f2e8] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="tile-rule absolute inset-x-0 top-0" /><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[0.95fr_1.05fr] lg:gap-20"><div className="motion-reveal"><p className="eyebrow text-[#8f5738]">{t("A cuisine with a point of view", "தனித்த பார்வையுடைய சமையல்")}</p><h2 className="mt-4 font-display text-5xl leading-[0.88] tracking-[-0.05em] text-[#641b20] sm:text-7xl">{t("The story is in the grind.", "அரைத்த மசாலாவில் கதை உள்ளது.")}</h2></div><div className="motion-reveal motion-delay-2 pt-2"><p className="max-w-xl text-base leading-8 text-[#5f4545] sm:text-lg">{t("Chettinad food is not one-note heat. It is layered: pepper and fennel, dry chillies and tamarind, roasted coconut and the patient work of a simmering pot. Karaikudi Chettinad Mess brings this balance to Abu Shagara.", "செட்டிநாடு உணவு வெறும் காரமல்ல. அது மிளகு, சோம்பு, மிளகாய், புளி, வறுத்த தேங்காய் மற்றும் பொறுமையான சமையலின் அடுக்குகள். காரைக்குடி செட்டிநாடு மெஸ் இந்த சமநிலையை அபு ஷகராவிற்குக் கொண்டு வருகிறது.")}</p><Link href="/story" className="editorial-link mt-8">{t("Read our story", "எங்கள் கதையைப் படியுங்கள்")} <ChevronRight size={16} /></Link></div></div></section>

    <section className="bg-[#321519] px-5 py-20 text-[#f7f2e8] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1320px]"><SectionTitle dark eyebrowEn="Chef’s table" eyebrowTa="சமையலறை சிறப்புகள்" titleEn="The dishes everyone makes room for." titleTa="எல்லோரும் இடம் ஒதுக்கும் உணவுகள்." bodyEn="Three crowd-favourites prepared with the bright spices and slow-built heat Chettinad food is known for." bodyTa="செட்டிநாடு உணவின் மிளிரும் மசாலா மற்றும் மெதுவாக உருவாகும் காரத்துடன் தயாரிக்கப்படும் மூன்று சிறப்புகள்." /><div className="mt-12 grid gap-5 md:grid-cols-3">{dishes.map((dish, index) => <article key={dish.name} className="dish-card motion-reveal group" style={{ animationDelay: `${100 + index * 110}ms` }}><div className="relative aspect-[3/4] overflow-hidden bg-[#4a2528]"><img src={dish.image} alt={`${dish.name} signature dish`} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.08]" /><div className="absolute inset-0 bg-gradient-to-t from-[#16090a]/75 via-transparent to-transparent" /><span className="absolute right-4 top-4 grid h-9 w-9 place-items-center rounded-full border border-white/30 bg-black/10 text-[10px] font-bold tracking-wider">{dish.number}</span><div className="absolute inset-x-5 bottom-5"><h3 className="font-display text-4xl leading-[0.9]">{t(dish.name, dish.ta)}</h3><p className="mt-2 text-sm leading-5 text-[#fff6e9]/75">{t(dish.caption, dish.taCaption)}</p></div></div></article>)}</div><Link href="/order" className="button-copper mt-9"><span>{t("Order these favourites", "இந்த சிறப்புகளை ஆர்டர் செய்யுங்கள்")}</span><ArrowUpRight size={16} /></Link></div></section>

    <section className="bg-[#eadfce] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1240px] gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:items-center"><div className="motion-reveal relative"><div className="absolute -left-3 -top-3 h-20 w-20 border-l border-t border-[#9a6a4a]" /><img src="/manus-storage/karaikudi-interior_4861be41.jpg" alt="Warm heritage-inspired dining space with teak furniture and brass lamp" className="h-[380px] w-full object-cover transition-transform duration-700 hover:scale-[1.015] sm:h-[520px]" /></div><div className="motion-reveal motion-delay-2 lg:pl-8"><SectionTitle eyebrowEn="Find our doorway" eyebrowTa="எங்கள் வாசலைக் கண்டுபிடியுங்கள்" titleEn="Chettinad warmth, in Abu Shagara." titleTa="அபு ஷகராவில் செட்டிநாடு அன்பு." bodyEn="Find Karaikudi Chettinad Mess in Abu Shagara, Sharjah. Call us directly for orders and enquiries." bodyTa="ஷார்ஜாவின் அபு ஷகராவில் காரைக்குடி செட்டிநாடு மெஸ்ஸைக் கண்டுபிடியுங்கள். ஆர்டர்கள் மற்றும் விசாரணைகளுக்கு நேரடியாக அழைக்கவும்." /><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="info-tile"><Phone size={18} /><span><b>+971 50 808 8154</b><small>06 533 9330 · 06 526 1010</small></span></div><div className="info-tile"><MapPin size={18} /><span><b>{t("Abu Shagara", "அபு ஷகரா")}</b><small>{t("Sharjah, UAE", "ஷார்ஜா, UAE")}</small></span></div></div><Link href="/location" className="button-primary mt-8"><span>{t("Location & contact", "இடம் மற்றும் தொடர்பு")}</span><ArrowUpRight size={16} /></Link></div></div></section>

    <section className="bg-[#f7f2e8] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1080px]"><div className="grid gap-8 border-b border-[#641b20]/15 pb-12 md:grid-cols-[1fr_auto]"><SectionTitle eyebrowEn="Words from the table" eyebrowTa="மேசையிலிருந்து வார்த்தைகள்" titleEn="Real diners deserve a real feed." titleTa="உண்மையான விருந்தினர்களுக்கு உண்மையான கருத்துகள்." bodyEn="We will only show genuine Google Reviews or verified guest feedback. No invented testimonials will appear here." bodyTa="உண்மையான Google Reviews அல்லது சரிபார்க்கப்பட்ட விருந்தினர் கருத்துகள் மட்டுமே இங்கே காட்டப்படும்." /><Link href="/reviews" className="editorial-link h-fit self-end">{t("Reviews setup", "கருத்துகள் அமைப்பு")} <ChevronRight size={16} /></Link></div><div className="motion-reveal mt-12 grid gap-6 md:grid-cols-3"><div className="md:col-span-2"><p className="font-display text-5xl leading-[0.9] text-[#641b20] sm:text-6xl">{t("No borrowed praise. Just a place for the real thing.", "கடன் வாங்கிய பாராட்டு இல்லை. உண்மைக்கு ஒரு இடம் மட்டும்.")}</p></div><div className="border-l border-[#9a6a4a] pl-6"><p className="eyebrow text-[#8f5738]">Google Reviews</p><p className="mt-3 text-sm leading-7 text-[#604547]">{t("The verified profile will be connected once the restaurant’s Google Business listing is ready.", "உணவகத்தின் Google Business பட்டியல் தயாரானதும் சரிபார்க்கப்பட்ட சுயவிவரம் இணைக்கப்படும்.")}</p></div></div></div></section>
  </>;
}
